FROM node:lts-alpine as build

RUN npm install -g serve

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8080

CMD [ "serve", "-s", "dist", "-l", "tcp://0.0.0.0:8080" ]