services:
  db : 
    image : postgres:15
    environment :
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports :
      - "${POSTGRES_PORT}:5432"
    
    volumes :
      - pgdata:/var/lib/postgresql/data

    networks:
      - back-tier
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    networks:
      - front-tier
      - back-tier

    volumes :
      - ./frontend:/app

    command: sh -c "npm install && npm run dev"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:3000"

    networks:
      - back-tier

    volumes :
      - ./backend:/app
      - node_modules:/app/node_modules

    command: sh -c "npm install && nodemon server.js"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"   # map to host port you want
    networks:
      - back-tier

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}

# This defines the named volume
volumes:
  node_modules:
  pgdata:
  pgadmin_data: