services:
  db : 
    image : postgres:15
    environment :
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports :
      - "${POSTGRES_PORT}:5432"
    
    volumes :
      - pgdata:/var/lib/postgresql/data

    networks:
      - back-tier
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    networks:
      - front-tier
      - back-tier

    volumes :
      - ./frontend:/app
      - /app/node_modules 

    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:3000"

    networks:
      - back-tier

    volumes :
      - ./backend:/app
      - node_modules:/app/node_modules

    command: nodemon server.js

  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - back-tier

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}

# This defines the named volume
volumes:
  node_modules:
  pgdata:
  pgadmin_data: