sonar.organization=amineboukhari
sonar.projectKey=amineBoukhari_Projet-Annuel-ESGI-4

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/__tests__/**
sonar.exclusions=**/node_modules/**,**/dist/**,**/__tests__/**

sonar.sourceEncoding=UTF-8
