name: SonarCloud

on:
  push:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
